### ISSUE TITLE
Error 404 on spec text link

### ISSUE THREAD

**Issue by thedaviddias** [tc39/proposal-ecma402-datetime-style#10]
It seems that the link inside the README file is redirecting to an 404 error.

I think it should be `https://raw.githubusercontent.com/tc39/proposal-ecma402-datetime-style/master/out` instead of `https://rawgit.com/zbraniecki/proposal-ecma402-datetime-style/master/out/`..

Good job on that proposal!

**Comment by littledan** [comment]
Fixed the link, thanks!
